### ISSUE TITLE
Resize Hero Image please

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Intellectual-Heritage#1]
Hey @ZMcGroarty Zac when you get a chance can you please resize the hero image with no red hue, we're ready to go live? Thank you!

**Comment by ZMcGroarty** [comment]
this one might be large but I want to see how it lays out. lets try it.

![hero_ih-min](https://user-images.githubusercontent.com/15017242/34956407-e1cda5da-f9f6-11e7-9fbb-58e06fabe6eb.png)

**Comment by CVE82** [comment]
Awesome thank you I'll pop it in now!
